const mongoose=require("mongoose");

const FishProductSchema=mongoose.Schema({

    productImage:{
        type:String,
    },
    productName:{
        type:String,
        require:true
    },
    productDescription:{
        type:String,
        require:true
    },
    productVeriety:{
        type:String,
        require:true
    },
    productStock:{
        type:Number,
        require:true
    },
    productPrice:{
        type:Number,
        require:true
    },
    productDiscount:{
        type:Number,
        require:true
    },
    productExpireDate:{
        type:Date,
        require:true
    },
    productManufactureDate:{
        type:Date,
        require:true
    },
    productLandingDate:{
        type:Date,
        require:true
    },
    productStockingDate:{
        type:Date,
        require:true
    },
    bulkWEight:{
        type:Number,
        require:true
    },
    nameOfFarmer:{
        type:String,
        require:true
    },
    addressOfFarmer:{
        type:String,
        require:true
    },
    mobileOfFarmer:{
        type:Number,
        require:true
    },
    landingLocation:{
        type:String,
        require:true
    },
    aquaticSource:{
        type:String,
        require:true
    },
    harvestedType:{
        type:String,
        require:true
    },
    batchNumber:{
        type:String,
        require:true
    },
    storageTemperature:{
        type:Number,
        require:true
    },
    tempStorageTemperature:{
        type:String,
        require:true
    },
    transportMethod:{
        type:String,
        require:true
    },
    listedDate:{
        type:Date,
        require:true
    },
    aOB:{
        type:Boolean,
        require:true
    },
    tOB:{
        type:Boolean,
        require:true
    },
    cOF:{
        type:Boolean,
        require:true
    },
    fOE:{
        type:Boolean,
        require:true
    },
    pOE:{
        type:Boolean,
        require:true
    },
    cOG:{
        type:Boolean,
        require:true
    },
    oOG:{
        type:Boolean,
        require:true
    },
    mOG:{
        type:Boolean,
        require:true
    }
})


const FishProduct = mongoose.model("FishProduct",FishProductSchema);
module.exports =FishProduct;