const mongoose=require("mongoose");

const MeatProductSchema=mongoose.Schema({

    productImage:{
        type:String,
    },
    productName:{
        type:String,
        require:true
    },
    productDescription:{
        type:String,
        require:true
    },
    productVeriety:{
        type:String,
        require:true
    },
    productStock:{
        type:Number,
        require:true
    },
    productPrice:{
        type:Number,
        require:true
    },
    productDiscount:{
        type:Number,
        require:true
    },
    productExpireDate:{
        type:Date,
        require:true
    },
    productManufactureDate:{
        type:Date,
        require:true
    },
    bulkWEight:{
        type:Number,
        require:true
    },
    nameOfFarmer:{
        type:String,
        require:true
    },
    addressOfFarmer:{
        type:String,
        require:true
    },
    mobileOfFarmer:{
        type:Number,
        require:true
    },
    livestockType:{
        type:String,
        require:true
    },
    farmLocation:{
        type:String,
        require:true
    },
    breadingstockDetails:{
        type:String,
        require:true
    },
    growthStage:{
        type:String,
        require:true
    },
    farmingPractice:{
        type:String,
        require:true
    },
    feedType:{
        type:String,
        require:true
    },
    slaughterMethod:{
        type:String,
        require:true
    },
    slaughterDate:{
        type:Date,
        require:true
    },
    batchNumber:{
        type:String,
        require:true
    },
    storageTemperature:{
        type:Number,
        require:true
    },
    processingMethod:{
        type:String,
        require:true
    },
    transportMethod:{
        type:String,
        require:true
    },
    fertilizerApplication:{
        type:[String],
        
    },
    listedDate:{
        type:Date,
        require:true
    }
})


const MeatProduct = mongoose.model("MeatProduct",MeatProductSchema);
module.exports =MeatProduct;